version: '3.5'

services:

  jenkins:
    image: docker.io/hoto/jenkinsfile-examples
    build: .
    ports:
    - target: 8080
      published: 8080
    volumes:
    - type: bind
      source: '/var/run/docker.sock'
      target: '/var/run/docker.sock'
      read_only: true
    networks:
    - jenkins-network
    tty: true

  jenkinsfile-loader:
    image: docker.io/hoto/jenkinsfile-loader:1.1.0
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      CONFIGS_XML_DIR: '/usr/local/src/configs'
      JENKINSFILES_DIR: '/usr/local/src/jenkinsfiles'
      DEBUG: 'false'
    volumes:
    - type: bind
      source: '${PWD}/configs'
      target: '/usr/local/src/configs'
      read_only: true
    - type: bind
      source: '${PWD}/jenkinsfiles'
      target: '/usr/local/src/jenkinsfiles'
      read_only: true
    depends_on:
    - jenkins
    networks:
    - jenkins-network
    tty: true

networks:
  jenkins-network:
